# This file was generated by GoReleaser. DO NOT EDIT.
cask "githubrel" do
  name "githubrel"
  desc "GitHub releases tracker CLI"
  homepage "https://github.com/vosiander/github-releases"
  version "0.9.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "githubrel"

  on_macos do
    on_intel do
      url "https://github.com/vosiander/github-releases/releases/download/v#{version}/githubrel_#{version}_darwin_amd64.tar.gz"
      sha256 "a8b68e4e41097a397d8e250a6f4975516abeae97df405b44c3f280b5ef45a024"
    end
    on_arm do
      url "https://github.com/vosiander/github-releases/releases/download/v#{version}/githubrel_#{version}_darwin_arm64.tar.gz"
      sha256 "480793958640e9477220defdb8775a70838d11fa5f170a52d8fe2b00a2e568bf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/vosiander/github-releases/releases/download/v#{version}/githubrel_#{version}_linux_amd64.tar.gz"
      sha256 "f5bc6d05bd92d98939172a211d9fda15ad9247464d9bd2f3201ffe66b345e6e0"
    end
    on_arm do
      url "https://github.com/vosiander/github-releases/releases/download/v#{version}/githubrel_#{version}_linux_arm64.tar.gz"
      sha256 "b40ae38ff56be4588a0e53faaaa3c6f49caf89631db764ccfb70f2dfb32f304e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/githubrel"]
    end
  end

  # No zap stanza required
end
