# This file was generated by GoReleaser. DO NOT EDIT.
cask "pgsnap" do
  name "pgsnap"
  desc "PostgreSQL backup and restore tool for Kubernetes"
  homepage "https://github.com/vosiander/pgsnap"
  version "1.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pgsnap"

  on_macos do
    on_intel do
      url "https://github.com/vosiander/pgsnap/releases/download/v#{version}/pgsnap_#{version}_darwin_amd64.tar.gz"
      sha256 "e882c907634809f89e7baffe08da4396c294389db656713e3bcc1a6e0b17c3bd"
    end
    on_arm do
      url "https://github.com/vosiander/pgsnap/releases/download/v#{version}/pgsnap_#{version}_darwin_arm64.tar.gz"
      sha256 "e025cddda7d7101fee0bf46a7803ac9781a04501ce55d2b5e4293741736df56e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/vosiander/pgsnap/releases/download/v#{version}/pgsnap_#{version}_linux_amd64.tar.gz"
      sha256 "3dc82590c0f77af36b7cf9ed9d7e9dce197d28bb1d5d0ea162fb3300304ae5f9"
    end
    on_arm do
      url "https://github.com/vosiander/pgsnap/releases/download/v#{version}/pgsnap_#{version}_linux_arm64.tar.gz"
      sha256 "88226767441d8b755a0ab2e0ad7ae5eca660020e34850bfd38a1f5510d83d778"
    end
  end

  # No zap stanza required
end
