# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgsnap < Formula
  desc "PostgreSQL backup and restore tool for Kubernetes"
  homepage "https://github.com/vosiander/pgsnap"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vosiander/pgsnap/releases/download/v1.0.0/pgsnap_1.0.0_darwin_amd64.tar.gz"
      sha256 "9170102e06cd52db94b2e049b43987f7128c545df110cbecb887d6921872401f"

      def install
        bin.install "pgsnap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vosiander/pgsnap/releases/download/v1.0.0/pgsnap_1.0.0_darwin_arm64.tar.gz"
      sha256 "62d9d879298e4fdae5bb7972d7803cdea9f0298b6d42fb002eae938f5997b9d5"

      def install
        bin.install "pgsnap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vosiander/pgsnap/releases/download/v1.0.0/pgsnap_1.0.0_linux_amd64.tar.gz"
      sha256 "78844f6f94e4549145de35c1c7b262c043ff9c5865a3b36c95acd6bd808bca8e"
      def install
        bin.install "pgsnap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vosiander/pgsnap/releases/download/v1.0.0/pgsnap_1.0.0_linux_arm64.tar.gz"
      sha256 "b04f86687b15ed2d75b6c98e2d5eb3f8bd9c61f33d2f1a90ceab96e2232b7418"
      def install
        bin.install "pgsnap"
      end
    end
  end

  test do
    system "#{bin}/pgsnap", "--version"
  end
end
