# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgsnap < Formula
  desc "PostgreSQL backup and restore tool for Kubernetes"
  homepage "https://github.com/vosiander/pgsnap"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vosiander/pgsnap/releases/download/v1.1.0/pgsnap_1.1.0_darwin_amd64.tar.gz"
      sha256 "46bd224e3e9d1ba46705864d9f98601c94877cc6caf834741f157689abaae11a"

      define_method(:install) do
        bin.install "pgsnap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vosiander/pgsnap/releases/download/v1.1.0/pgsnap_1.1.0_darwin_arm64.tar.gz"
      sha256 "b3b41e78a85abe97da2e5131686c65d2d496ec88130dac62b66984bda087201b"

      define_method(:install) do
        bin.install "pgsnap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vosiander/pgsnap/releases/download/v1.1.0/pgsnap_1.1.0_linux_amd64.tar.gz"
      sha256 "9b182b14811ce5481ac3128011cca75285da67498cef66dc324063948807b1aa"
      define_method(:install) do
        bin.install "pgsnap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vosiander/pgsnap/releases/download/v1.1.0/pgsnap_1.1.0_linux_arm64.tar.gz"
      sha256 "749c28e6623462d7c8d76b417e1ef8f7cf9497b8087b033bfa8ab1115760f05d"
      define_method(:install) do
        bin.install "pgsnap"
      end
    end
  end

  test do
    system "#{bin}/pgsnap", "--version"
  end
end
