# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Repoaudit < Formula
  desc "Automated security audit for Git repositories"
  homepage "https://github.com/vosiander/repo-audit"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vosiander/repo-audit/releases/download/v0.1.0/repoaudit_0.1.0_darwin_amd64.tar.gz"
      sha256 "c62a879021ce3e550eb3a566ac6964445323279231bbd0e92ae9a9fbf5682aa9"

      define_method(:install) do
        bin.install "repoaudit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vosiander/repo-audit/releases/download/v0.1.0/repoaudit_0.1.0_darwin_arm64.tar.gz"
      sha256 "3120466b86f546a59d2300724b97de2114eaa4a5bade85438a22421607daf6c8"

      define_method(:install) do
        bin.install "repoaudit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vosiander/repo-audit/releases/download/v0.1.0/repoaudit_0.1.0_linux_amd64.tar.gz"
      sha256 "b9b60b227ab668f2c1c04c56025e92b9b71f9c0673c5513bfff28f9389ec8be2"
      define_method(:install) do
        bin.install "repoaudit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vosiander/repo-audit/releases/download/v0.1.0/repoaudit_0.1.0_linux_arm64.tar.gz"
      sha256 "af00d21efc99552b62cc6b5928c8f31338ae716337a3271d89615e81b9b33584"
      define_method(:install) do
        bin.install "repoaudit"
      end
    end
  end

  test do
    system "#{bin}/repoaudit", "--help"
  end
end
